
server:
  port: 9090
  servlet:
    context-path: /sb-dev-demplate
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

# DataSource Config
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# Logger Config sql打印
logging:
    level:
      team.shiver: debug
#    path:





